apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasteease-db-deployment
  namespace: tasteease
  labels:
    app: tasteease-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasteease-database-pod
  template:
    metadata:
      labels:
        app: tasteease-database-pod
    spec:
      containers:
        - name: tasteease-postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "tasteease"
            - name: POSTGRES_PASSWORD
              value: "tasteease"
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"

        - name: tasteease-pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "taste@tasteease.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "@123456"
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "False"
          resources:
            limits:
              cpu: "500m"
              memory: "100Mi"
