apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-api
  namespace: tasteease
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tasteease-api-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
