apiVersion: v1
kind: Pod
metadata:
  name: tasteease-database-pod
  namespace: tasteease
  labels:
    app: tasteease-database-pod
spec:
  containers:
    - name: tasteease-postgresql
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: "tasteease"
        - name: POSTGRES_PASSWORD
          value: "tasteease"
        - name: PGDATA
          value: "/data/postgres"
      ports:
        - containerPort: 5432
      resources:
        limits:
          cpu: "1"
          memory: "256Mi"

    - name: tasteease-pgadmin
      image: dpage/pgadmin4:latest
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "taste@tasteease.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "@123456"
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "256Mi"
