apiVersion: v1
kind: Pod
metadata:
  name: tasteease-database-pod
  namespace: tasteease
  labels:
    app: tasteease-database-pod
spec:
  containers:
    - name: tasteease-postgresql
      image: postgres:latest
      env:
        - name: POSTGRES_USER
          value: "tasteease"
        - name: POSTGRES_PASSWORD
          value: "tasteease"
        - name: PGDATA
          value: "/data/postgres"
      ports:
        - containerPort: 5432
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"

    - name: tasteease-pgadmin
      image: dpage/pgadmin4:latest
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "taste@tasteease.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "@123456"
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False"
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: tasteease-api-pod
  namespace: tasteease
  labels:
    app: tasteease-api-pod
spec:
  containers:
    - name: tasteease-api
      image: estrng/tasteease:0.0.16
      ports:
        - containerPort: 80
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: SECRETS_PATH
          value: /app/secrets/
      resources:
        limits:
          cpu: "1"
          memory: "512Mi"
        requests:
          cpu: "0.5"
          memory: "256Mi"
      volumeMounts:
        - name: secrets
          mountPath: /app/secrets/appsettings.json
          subPath: appsettings.json
  volumes:
    - name: secrets
      configMap:
        name: appsettings-taste-ease
