apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-tasteease-api
  labels:
    app: cfg-tasteease-api
data:
  ASPNET_ENVIRONMENT: "Development"


apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-taste-ease
  namespace: tasteease
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "DefaultConnection": "Host=tasteease-database-service.tasteease.svc.cluster.local;Port=80;Database=taste-ease;Username=tasteease;Password=tasteease"
      }
    }